//Teste de Requisições REST
@baseURL = http://localhost:4000
@id = 615b7d6d6e89af4250050755

###
//GET - Lista as informações do usuário pelo ID informado
GET {{baseURL}}/usuario/
Content-Type: application/json

###
//GET - Lista as informações do usuário pelo ID informado
GET {{baseURL}}/usuario/{{id}}
Content-Type: application/json

###
//POST - Cadastra um usuário
POST {{baseURL}}/usuario
Content-Type: application/json

{
    "nome": "João Pereira da Silva",
    "cpf": "45796512356",
    "telefone": "11624145763",
    "data_nascimento": "2000-07-27",
    "endereco.logradouro": "Av. Tiradentes",
    "endereco.bairro": "Centro",
    "endereco.cidade": "Sorocaba",
    "endereco.uf": "SP",
    "endereco.numero": "150",
    "endereco.cep": "13308441",
    "endereco.complemento": "",
    "email": "joao.silva@hotmail.com",
    "senha": "joaosilva123"
}

###
//POST - Altera um usuário
PUT {{baseURL}}/usuario
Content-Type: application/json

{
    "_id": "615b7d6d6e89af4250050755",
    "nome": "João Pereira da Silva",
    "cpf": "31577678443",
    "telefone": "15456871236",
    "data_nascimento": "2000-03-10",
    "endereco.logradouro": "Praça Pe. Miguel",
    "endereco.bairro": "Centro",
    "endereco.cidade": "Itu",
    "endereco.uf": "SP",
    "endereco.numero": "1320",
    "endereco.cep": "",
    "endereco.complemento": "",
    "email": "jose.silva@gmail.com",
    "senha": "josesilva"
}

###
// DELETE - Apaga a categoria pelo id
DELETE {{baseURL}}/usuario/{{id}}
Content-Type: application/json