//Teste de Requisições REST
@baseURL = http://localhost:4000
@id = 615a421d4b82e7c183c50f45

###
//GET - Lista as informações do usuário pelo ID informado
GET {{baseURL}}/usuario/
Content-Type: application/json

###
//GET - Lista as informações do usuário pelo ID informado
GET {{baseURL}}/usuario/{{id}}
Content-Type: application/json

###
//POST - Cadastra um usuário
POST {{baseURL}}/usuario
Content-Type: application/json

{
    "nome": "Luana Maria Gomes",
    "cpf": "87463214569",
    "telefone": "11624157863",
    "data_nascimento": "1994-10-01",
    "endereco.logradouro": "Rua Saturno",
    "endereco.bairro": "Jd. Novo Mundo",
    "endereco.cidade": "Salto",
    "endereco.uf": "SP",
    "endereco.numero": "654",
    "endereco.cep": "145314865",
    "endereco.complemento": "casa",
    "email": "luana.gomes@hotmail.com",
    "senha": "luana351"
}

###
//POST - Altera um usuário
PUT {{baseURL}}/usuario
Content-Type: application/json

{
    "_id": "615a421d4b82e7c183c50f45",
    "nome": "José Alves Silva",
    "cpf": "31577678443",
    "telefone": "11945213287",
    "data_nascimento": "2000-03-10",
    "endereco.logradouro": "Praça Pe. Miguel",
    "endereco.bairro": "Centro",
    "endereco.cidade": "Itu",
    "endereco.uf": "SP",
    "endereco.numero": "1320",
    "endereco.cep": "",
    "endereco.complemento": "",
    "email": "jose.silva@gmail.com",
    "senha": "josesilva"
}

###
// DELETE - Apaga a categoria pelo id
DELETE {{baseURL}}/usuario/{{id}}
Content-Type: application/json